# Generated by Django 2.2.2 on 2019-07-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionData',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('problemData', models.FileField(blank=True, upload_to='portal/runCode')),
                ('inputFile', models.FileField(blank=True, null=True, upload_to='portal/runCode')),
                ('submissionId', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('outputFile', models.FileField(blank=True, null=True, upload_to='portal/runCode')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
